name = "ly-ai"
compatibility_date = "2025-04-04"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production]
node_version = "18.18.0"
node_compat = true  # 启用 Node.js 兼容模式